### ISSUE TITLE
Draw the current FPS and lag into window title 

### ISSUE THREAD

**Issue by CHEF-KOCH** [GlitchCog/ChatGameFontificator#3]
I wish we could get an option to show the current fps and 'lag' directly into the titlebar. I use another program which have such ability, please take a look over [here](https://github.com/lifning/padpyght).

![fps](https://cloud.githubusercontent.com/assets/727123/15103709/fc02641e-15ae-11e6-9d80-1d1701090cc4.png)

**Comment by GlitchCog** [comment]
The chat display window on the Fontificator doesn't display like a game, which refreshes itself at a set rate regardless of its contents. For example, if no message is currently being drawn, the window just rests with its existing content at 0 FPS. If the message speed is set to MAX characters per second, then every posted message represents a single frame of redrawing, so the rate the messages post is effectively the FPS, at most one or two per second. If the message speed is set to something less than MAX but more than whatever char/sec value results in the delay speed specified in the ConfigMessage.SHORTEST_DELAY variable (currently set to 67 ms), each character written represents a frame redrawn, so the message rate becomes the characters per second value. Anything under the SHORTEST_DELAY value just defaults to 15 FPS (1000 ms per second / 67 ms = 14.9 redraws per second) and it makes up the speed difference by sometimes adding more than one new character per redraw.

So essentially, the Fontificator maxes out at an unimpressive 15 fps, and runs at much less than that if you have the message speed set low enough. But it's not animating a game screen containing a player character jumping over enemies or anything. I went with this model over a smoother-looking set redraw model because the animation being drawn is a lot closer to a word processor than a game, and setting a nice smooth FPS would kick it up into a whole other tier of CPU usage.

This is broadly how I would implement the change to run it at a faster redraw rate like a game:
You'd need to call ChatPanel.setIgnoreRepaint(true) and manage calling the ChatPanel.paint(Graphics) via the usual call to repaint() manually from some external timer scheduler event loop... and Java's Swing is decidedly not the best timer to use for getting a good safe refresh rate out of Java. I'd recommend rolling your own update loop all in the same thread that manages the passed time and takes how long it takes to update to subtract from the remaining available time. Basically it would need to be run like a full game loop. This is what would make it a lot more CPU intensive, mostly to redraw the exact same static bit of text in between rolling out the next new character. Then pull out the 
else if (1000L / messageConfig.getMessageSpeed() < ConfigMessage.SHORTEST_DELAY)
block (which limits the delay if it would otherwise redraw too fast) from the Message.incrementDrawCursor() method (which is essentially the update call if this were a game loop). Then you'd have a proper game loop wrapped around the update and draw logic, handling the math of stuff like when there's not enough time to redraw if the update gets too intense, which then drops the FPS and limiting a max FPS if everything is running fast enough to draw a lot, which would likely be true given the relatively small amount the Fontificator has to update.
