### ISSUE TITLE
A Java Exception has occurred. - Since Java 7 Update 49

### ISSUE THREAD

**Issue by CHEF-KOCH** [GlitchCog/ChatGameFontificator#5]
I fresh installed Win 10 x64 with latest stable Java and I got this now, other programs like chatty working fine. 

![e2](https://cloud.githubusercontent.com/assets/727123/15454775/193ad0a0-2042-11e6-8a9c-960013bc0379.png)

Other programs like chatty working fine so I think it's an issue since Oracle seems to changed some stuff.

Any workaround to fix this? Sadly I not found any Log, maybe this would be helpful to add in the future. 

Edit: I may could try Java 8 but currently Android Studio have some troubles with it.

**Comment by GlitchCog** [comment]
I suspect this and Google wrongly report Download as 'harmful' bug are related. I think it happened when the JRE on my classpath in Eclipse changed when I reinstalled my local OS. Then the JAR I built locally, which is the one I uploaded had some suspicious mismatch or something in its MANIFEST file.

**Comment by CHEF-KOCH** [comment]
I think you posted this into the wrong ticket, I think you mean [this](https://github.com/GlitchCog/ChatGameFontificator/issues/4).

**Comment by GlitchCog** [comment]
No, I mean the comment for both. It's just a theory for the malware bug, but I'm next to certain the MANIFEST discrepancy is what's causing this bug, because I found some resources pointing to that. I'm almost ready to build a new JAR with some other changes, and I manually deleted the Eclipse 'target' directory, so hopefully that'll do the trick to fix this.

**Comment by GlitchCog** [comment]
Please try the new JAR file to see if it's fixed. I built it with a Maven install, so hopefully that took care of it. If not, I'll redouble my efforts. I can't test it myself because I am fortunate enough not to have Windows 10!

**Comment by CHEF-KOCH** [comment]
Sadly exactly the same error. 

![29f](https://cloud.githubusercontent.com/assets/727123/15497048/ee84ceda-2198-11e6-958c-6c8f672df804.jpg)

**Comment by GlitchCog** [comment]
Sorry it's still broken for you.

If you want to see the exception, it's already being fed into a console appender, so if you run it on the command line with:
java -jar ChatGameFontificator.jar
you should see any logging messages and exceptions there.

**Comment by CHEF-KOCH** [comment]
```bash
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/glitchcog/fontificator/FontificatorMain : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by GlitchCog** [comment]
Ah, yeah. That makes sense. I didn't notice you said you _could_ install Java 1.8, meaning you have some Java 1.7 installed, right? I thought you were all up to date with 1.8 because you said you were using the latest stable Java.

The build currently targets 1.8, so I'll just target 1.7. That's better anyhow since it's more inclusive. I think I can fix this for you shortly.

**Comment by GlitchCog** [comment]
Try the new JAR. I changed the build target version to 1.6, which should fix your problem! Also, although it wouldn't have helped here because the exception was before the GUI was visible, I added a "Debug Mode" to the Help menu, which adds a tab to show the log and associated exceptions. I have plans to add stuff to that tab later as well, but for now, it's just a place to view the log.

**Comment by CHEF-KOCH** [comment]
Well latest stable Java is 1.7. The thing about 1.8 is what I said, Android Studio not likes it, I don't know if that is fixed now, but it had DEX problems. Maybe I will try it but 1.7 is long time approved to work well. 

Well I tried the new version and:
![download](https://cloud.githubusercontent.com/assets/727123/15569689/6c14b032-2332-11e6-908b-f316e90c79be.jpg)
