### ISSUE TITLE
Messages not appearing in chat window

### ISSUE THREAD

**Issue by alucardtepes** [GlitchCog/ChatGameFontificator#7]
I'm getting no messages appearing in the chat window. They're being captured in the configuration window and look like: 

:synthpopisback!synthpopisback@synthpopisback.tmi.twitch.tv PRIVMSG #synthpopisback :testing

They all have this "PRIVMSG" bit and I'm suspicious that that's doing it, but I can't figure out how to fix that and it worked less than 24 hours before I noticed it.

**Comment by GlitchCog** [comment]
I just tested with the latest JAR (October 20, 2016), and I can't reproduce your issue. The messages you saw on the configuration window (bottom of the Connection tab) are supposed to be there. It's the raw message text from the IRC server. Here are examples of what they might look like.

For a streamer in his or her own channel:
`@badges=broadcaster/1;color=#5F9EA0;display-name=GlitchCog;emotes=;id=16181d86-c946-4d6e-971e-930479970e15;mod=0;room-id=57318954;sent-ts=1479728423451;subscriber=0;tmi-sent-ts=1479728423536;turbo=0;user-id=57318954;user-type= :glitchcog!glitchcog@glitchcog.tmi.twitch.tv PRIVMSG #glitchcog :Testing, testing, one, two, three.`

And for a regular user in someone else's channel:
`@badges=;color=;display-name=GlitchCogBot;emotes=;id=ad8155a4-844d-4291-8f11-a98e90fc551a;mod=0;room-id=57318954;sent-ts=1479728547696;subscriber=0;tmi-sent-ts=1479728547780;turbo=0;user-id=86136112;user-type= :glitchcogbot!glitchcogbot@glitchcogbot.tmi.twitch.tv PRIVMSG #glitchcog :Test message, one two three.`

The PRIVMSG bit is just the IRC protocol for any message sent. It's "private" in the sense that it's specific for that IRC channel:

[IRC specs on PRIVMSG](https://tools.ietf.org/html/rfc1459#page-32)

> PRIVMSG and NOTICE are the only messages available which actually perform delivery of a text message from one client to another

> PRIVMSG is used to send private messages between users.  <receiver> is the nickname of the receiver of the message.  <receiver> can also be a list of names or channels separated with commas.

There are, however, lots of configurations that could render the chat window in the Fontificator with no text. A few of them are listed in the [More Information](https://github.com/GlitchCog/ChatGameFontificator/#more-information-for-the-especially-curious) section of the Readme for this project under the "Why don't I see any messages?" section. You're definitely connected, so skip those possibilities. But the quickest way to check is to just click File... Restore Default Configuration. If you still don't see messages, then there might be something else wrong.

Oh, also, don't forget to close and re-open the program. Resetting your computer might be useful too. Sometimes glitches are one-off things that get fixed like that.

Please let me know if you get any results from this. Otherwise, please post further information about what happened so I can try to recreate the error.

Thanks!

**Comment by alucardtepes** [comment]
Restoring the default config worked for now. I'll load up the old config and turn on debug mode so I can grab the exceptions it was throwing. There was definitely something going on with that config that was causing all sorts of draw errors in the chat window AND the configurator. I'll let you know. Thanks.

**Comment by GlitchCog** [comment]
Do you have the .cgf file still of the broken configuration? That might help me identify what went wrong. Thanks.

**Comment by GlitchCog** [comment]
Please let me know if you want to reopen this. I suspect it's a specific configuration error, and I can't manage to reproduce it. Thanks!
